# These are supported funding model platforms

github: [isnot]
patreon: isnot
open_collective: isnot
ko_fi: isnot
tidelift: isnot/iitc-plugin-bookmarks-switcher
community_bridge: iitc-plugin-bookmarks-switcher
liberapay: isnot
issuehunt: isnot
otechie: isnot
custom: https://github.com/isnot/iitc-plugin-bookmarks-switcher
